[pytest]
# Diretório raiz dos testes
testpaths = app/tests

# Mostra nomes completos dos testes e saída colorida
addopts = -v --color=yes --tb=short

# Define o encoding padrão
console_output_style = classic

# Evita erro de importação de 'app'
pythonpath = .

# Desabilita warnings chatos do SQLAlchemy
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
