"""msg

Revision ID: d8b27837a229
Revises: 
Create Date: 2025-11-16 07:05:21.899694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b27837a229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_centros_trabalho_id'), table_name='centros_trabalho')
    op.drop_table('centros_trabalho')
    op.drop_index(op.f('ix_units_of_measure_id'), table_name='units_of_measure')
    op.drop_table('units_of_measure')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sales_orders_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_maquinas_id'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_index(op.f('ix_unidades_medida_id'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_product_materials_id'), table_name='product_materials')
    op.drop_table('product_materials')
    op.drop_index(op.f('ix_route_operations_id'), table_name='route_operations')
    op.drop_table('route_operations')
    op.drop_index(op.f('ix_material_orders_id'), table_name='material_orders')
    op.drop_table('material_orders')
    op.drop_table('operacao_centro_trabalho')
    op.drop_index(op.f('ix_materiais_codigo'), table_name='materiais')
    op.drop_index(op.f('ix_materiais_id'), table_name='materiais')
    op.drop_table('materiais')
    op.drop_index(op.f('ix_production_order_operations_id'), table_name='production_order_operations')
    op.drop_table('production_order_operations')
    op.drop_index(op.f('ix_operacoes_id'), table_name='operacoes')
    op.drop_table('operacoes')
    op.drop_index(op.f('ix_work_centers_id'), table_name='work_centers')
    op.drop_table('work_centers')
    op.drop_index(op.f('ix_sales_order_items_id'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_index(op.f('ix_production_routes_id'), table_name='production_routes')
    op.drop_table('production_routes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_routes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('production_routes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='production_routes_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='production_routes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_production_routes_id'), 'production_routes', ['id'], unique=False)
    op.create_table('sales_order_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sales_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('sales_order_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('sales_order_items_sales_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_order_items_pkey'))
    )
    op.create_index(op.f('ix_sales_order_items_id'), 'sales_order_items', ['id'], unique=False)
    op.create_table('work_centers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('work_centers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='work_centers_pkey'),
    sa.UniqueConstraint('name', name='work_centers_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_work_centers_id'), 'work_centers', ['id'], unique=False)
    op.create_table('operacoes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('operacoes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='operacoes_pkey'),
    sa.UniqueConstraint('nome', name='operacoes_nome_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_operacoes_id'), 'operacoes', ['id'], unique=False)
    op.create_table('production_order_operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planned_operation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planned_work_center_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_machine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_operation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_work_center_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_machine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('planned_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('planned_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('produced_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actual_machine_id'], ['machines.id'], name=op.f('production_order_operations_actual_machine_id_fkey')),
    sa.ForeignKeyConstraint(['actual_operation_id'], ['operations.id'], name=op.f('production_order_operations_actual_operation_id_fkey')),
    sa.ForeignKeyConstraint(['actual_work_center_id'], ['work_centers.id'], name=op.f('production_order_operations_actual_work_center_id_fkey')),
    sa.ForeignKeyConstraint(['planned_machine_id'], ['machines.id'], name=op.f('production_order_operations_planned_machine_id_fkey')),
    sa.ForeignKeyConstraint(['planned_operation_id'], ['operations.id'], name=op.f('production_order_operations_planned_operation_id_fkey')),
    sa.ForeignKeyConstraint(['planned_work_center_id'], ['work_centers.id'], name=op.f('production_order_operations_planned_work_center_id_fkey')),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], name=op.f('production_order_operations_production_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('production_order_operations_pkey'))
    )
    op.create_index(op.f('ix_production_order_operations_id'), 'production_order_operations', ['id'], unique=False)
    op.create_table('materiais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unidade_medida_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque_atual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('preco_unitario', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['unidade_medida_id'], ['unidades_medida.id'], name=op.f('materiais_unidade_medida_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('materiais_pkey'))
    )
    op.create_index(op.f('ix_materiais_id'), 'materiais', ['id'], unique=False)
    op.create_index(op.f('ix_materiais_codigo'), 'materiais', ['codigo'], unique=True)
    op.create_table('operacao_centro_trabalho',
    sa.Column('operacao_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('centro_trabalho_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['centro_trabalho_id'], ['centros_trabalho.id'], name=op.f('operacao_centro_trabalho_centro_trabalho_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], name=op.f('operacao_centro_trabalho_operacao_id_fkey'), ondelete='CASCADE')
    )
    op.create_table('material_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('material_orders_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], name=op.f('material_orders_production_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('material_orders_pkey'))
    )
    op.create_index(op.f('ix_material_orders_id'), 'material_orders', ['id'], unique=False)
    op.create_table('route_operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('operation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_center_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sequence', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('standard_time_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('route_operations_machine_id_fkey')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('route_operations_operation_id_fkey')),
    sa.ForeignKeyConstraint(['route_id'], ['production_routes.id'], name=op.f('route_operations_route_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], name=op.f('route_operations_work_center_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('route_operations_pkey'))
    )
    op.create_index(op.f('ix_route_operations_id'), 'route_operations', ['id'], unique=False)
    op.create_table('product_materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('product_materials_material_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_materials_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_materials_pkey'))
    )
    op.create_index(op.f('ix_product_materials_id'), 'product_materials', ['id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('operations_pkey')),
    sa.UniqueConstraint('name', name=op.f('operations_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_table('production_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('planned', 'in_production', 'finished', 'cancelled', name='productionorderstatus'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sales_order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('production_orders_product_id_fkey')),
    sa.ForeignKeyConstraint(['route_id'], ['production_routes.id'], name=op.f('production_orders_route_id_fkey')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], name=op.f('production_orders_sales_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('production_orders_pkey')),
    sa.UniqueConstraint('code', name=op.f('production_orders_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.create_table('unidades_medida',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sigla', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('unidades_medida_pkey')),
    sa.UniqueConstraint('nome', name=op.f('unidades_medida_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('sigla', name=op.f('unidades_medida_sigla_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_unidades_medida_id'), 'unidades_medida', ['id'], unique=False)
    op.create_table('maquinas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('centro_trabalho_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['centro_trabalho_id'], ['centros_trabalho.id'], name=op.f('maquinas_centro_trabalho_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('maquinas_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('maquinas_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_maquinas_id'), 'maquinas', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('net_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gross_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('parent_product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], name=op.f('products_parent_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey')),
    sa.UniqueConstraint('code', name=op.f('products_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('customer', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('planned', 'in_production', 'finished', 'cancelled', name='salesorderstatus'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_orders_pkey')),
    sa.UniqueConstraint('order_number', name=op.f('sales_orders_order_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sales_orders_id'), 'sales_orders', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('materials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('unit_of_measure_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['unit_of_measure_id'], ['units_of_measure.id'], name=op.f('materials_unit_of_measure_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('materials_pkey')),
    sa.UniqueConstraint('code', name=op.f('materials_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('units_of_measure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('abbreviation', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('units_of_measure_pkey')),
    sa.UniqueConstraint('abbreviation', name=op.f('units_of_measure_abbreviation_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('name', name=op.f('units_of_measure_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_units_of_measure_id'), 'units_of_measure', ['id'], unique=False)
    op.create_table('centros_trabalho',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('centros_trabalho_pkey')),
    sa.UniqueConstraint('nome', name=op.f('centros_trabalho_nome_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_centros_trabalho_id'), 'centros_trabalho', ['id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('work_center_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['work_center_id'], ['work_centers.id'], name=op.f('machines_work_center_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('machines_pkey')),
    sa.UniqueConstraint('code', name=op.f('machines_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    # ### end Alembic commands ###
